// @ts-check

import react from "@astrojs/react";
import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";
import mermaid from "astro-mermaid";

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: "(WIP!) Jellyfin Community Guides",
			social: [
				{
					icon: "github",
					label: "GitHub",
					href: "https://github.com/jellyfin-community-guides/jellyfin-community-guides.github.io",
				},
			],
			sidebar: [
				{
					label: "Guides",
					items: [
						"guides/get-started",
						"guides/example",
						// Explicit groups: an autogenerated one is labelled with its directory name
						{
							label: "Remote access",
							items: [{ autogenerate: { directory: "guides/remote-access" } }],
						},
						{
							label: "Reverse proxy",
							items: [{ autogenerate: { directory: "guides/reverse-proxy" } }],
						},
					],
				},
				{
					label: "Reference",
					items: [{ autogenerate: { directory: "reference" } }],
				},
			],
			customCss: ["./src/styles/sidebar.css"],
		}),
		mermaid(),
		react(),
	],
});
